set SEARCH_PATH to CARABI_KERNEL;

drop table MESSAGE_EXTENSION_TYPE;
drop table CARABI_PRODUCT_VERSION;
drop table CARABI_PRODUCTION;
drop table ORACLE_PARAMETER;
drop table ORACLE_QUERY;
drop table QUERY_CATEGORY;
drop table USER_LOGON;
drop table PHONE;
drop table PHONE_TYPE;
drop table ALLOWED_SCHEMAS;
drop table PERSONAL_TEMPORARY_CODE;
drop table USER_AT_SERVER_ENTER;
drop table USER_HAS_ROLE;
drop table ROLE_HAS_PERMISSION;
drop table USER_HAS_PERMISSION;
drop table USER_ROLE;
drop table USER_PERMISSION;
drop table RELATION_HAS_TYPE;
drop table USER_RELATION_TYPE;
drop table USER_RELATION;
drop table CARABI_USER;
drop table USER_STATUS;
drop table THUMBNAIL;
drop table FILE;
drop table APPSERVER;
drop table CONNECTION_SCHEMA;
drop view DUAL;

drop sequence connection_schema_id_gen;
drop sequence appserver_id_gen;
drop sequence file_id_gen;
drop sequence status_id_gen;
drop sequence user_id_gen;
drop sequence user_relation_id_gen;
drop sequence relation_type_id_gen;
drop sequence permission_id_gen;
drop sequence role_id_gen;
drop sequence phone_type_id_gen;
drop sequence phone_id_gen;
drop sequence category_id_gen;
drop sequence query_id_gen;
drop sequence parameter_id_gen;
drop sequence production_id_gen;
drop sequence product_version_id_gen;
drop sequence extension_type_id_gen

drop schema CARABI_KERNEL restrict;
commit;
